Repository aybolid/note-in-md, pull requests merged in 2023-07, with the labels that each got.

#5 fixes + improvements
  client/src/components/test/TestAuth.tsx
  client/src/contexts/AuthContext.tsx
  client/src/lib/axios/auth.ts
  client/src/utils/localStorage.ts
  server/DOCS.md
  server/handlers/authHandler.ts
  server/handlers/baseHandler.ts
  server/utils/jwt.ts
Labels: enhancement

#7 Notes handler + middleware
  server/DOCS.md
  server/app.ts
  server/handlers/authHandler.ts
  server/handlers/baseHandler.ts
  server/handlers/noteHandler.ts
  server/handlers/userHandler.ts
  server/middleware/noteMiddleware.ts
  server/models/Note.ts
  server/models/User.ts
  server/routers/noteRouter.ts
  server/routers/userRouter.ts
  server/utils/getTokenFromReq.ts
Labels: documentation, enhancement

#8 add btn component
  client/.storybook/main.ts
  client/.storybook/preview.ts
  client/package.json
  client/src/App.tsx
  client/src/index.css
  client/src/stories/Button.stories.ts
  client/src/stories/Button.tsx
  client/src/stories/Button/Button.stories.tsx
  client/src/stories/Button/Button.tsx
  client/src/stories/Header.stories.ts
  client/src/stories/Header.tsx
  client/src/stories/button.css
  client/src/stories/header.css
  client/tailwind.config.js
  client/yarn.lock
Labels: enhancement

#13 router, protected route, error page
  client/index.html
  client/src/App.tsx
  client/src/components/test/TestAuth.tsx
  client/src/components/utils/ProtectedRoute.tsx
  client/src/contexts/AuthContext.tsx
  client/src/index.css
  client/src/pages/AboutPage.tsx
  client/src/pages/AuthPage.tsx
  client/src/pages/ErrorPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/MarkdownTutorialPage.tsx
  client/src/pages/UserProfilePage.tsx
  client/src/stories/Button/Button.tsx
Labels: enhancement

#14 fix button
  client/src/stories/Button/Button.stories.tsx
  client/src/stories/Button/Button.tsx
Labels: enhancement

#16 10 themecontext
  client/package.json
  client/src/App.tsx
  client/src/components/ThemeToggler/ThemeToggler.tsx
  client/src/contexts/ThemeContext.tsx
  client/src/index.css
  client/src/main.tsx
  client/yarn.lock
Labels: enhancement

#22 basic layout + minor fixes
  client/.storybook/preview.ts
  client/public/bg-dark.svg
  client/public/bg-light.svg
  client/public/vite.svg
  client/src/App.tsx
  client/src/components/RootLayout/Aside.tsx
  client/src/components/RootLayout/Header.tsx
  client/src/components/RootLayout/index.tsx
  client/src/components/ThemeToggler/ThemeToggler.tsx
  client/src/components/test/TestAuth.tsx
  client/src/contexts/ThemeContext.tsx
  client/src/hooks/useOutsideClick.ts
  client/src/hooks/useScrollLock.ts
  client/src/index.css
  client/src/pages/ErrorPage.tsx
  client/src/pages/UserProfilePage.tsx
  client/src/stories/Introduction.mdx
  client/src/stories/assets/code-brackets.svg
  client/src/stories/assets/colors.svg
  client/src/stories/assets/comments.svg
  client/src/stories/assets/direction.svg
  client/src/stories/assets/flow.svg
  client/src/stories/assets/plugin.svg
  client/src/stories/assets/repo.svg
  client/src/stories/assets/stackalt.svg
  client/src/stories/components/Button.stories.tsx
  client/src/stories/components/Button.tsx
Labels: enhancement

#25 17 authform
  client/package.json
  client/src/components/AuthForm/AuthForm.tsx
  client/src/components/AuthForm/LogInForm.tsx
  client/src/components/AuthForm/SignUpForm.tsx
  client/src/components/AuthForm/validateSchema.ts
  client/src/index.css
  client/src/main.tsx
  client/src/pages/AuthPage.tsx
  client/src/stories/LabeledInput/LabeledInput.stories.tsx
  client/src/stories/LabeledInput/LabeledInput.tsx
  client/tailwind.config.js
  client/yarn.lock
Labels: enhancement

#27 prettier 💅
  client/.eslintrc.cjs
  client/.storybook/main.ts
  client/.storybook/preview.ts
  client/postcss.config.js
  client/prettier.config.cjs
  client/prettier.config.mjs
  client/src/App.tsx
  client/src/components/AuthForm/AuthForm.tsx
  client/src/components/AuthForm/LogInForm.tsx
  client/src/components/AuthForm/SignUpForm.tsx
  client/src/components/AuthForm/validateSchema.ts
  client/src/components/RootLayout/Aside.tsx
  client/src/components/RootLayout/Header.tsx
  client/src/components/RootLayout/index.tsx
  client/src/components/ThemeToggler/ThemeToggler.tsx
  client/src/components/test/TestAuth.tsx
  client/src/components/utils/ProtectedRoute.tsx
  client/src/contexts/AuthContext.tsx
  client/src/contexts/ThemeContext.tsx
  client/src/hooks/useOutsideClick.ts
  client/src/hooks/useScrollLock.ts
  client/src/index.css
  client/src/lib/axios/auth.ts
  client/src/main.tsx
  client/src/pages/AboutPage.tsx
  client/src/pages/AuthPage.tsx
  client/src/pages/ErrorPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/MarkdownTutorialPage.tsx
  client/src/pages/UserProfilePage.tsx
  client/src/stories/LabeledInput/LabeledInput.stories.tsx
  client/src/stories/LabeledInput/LabeledInput.tsx
  client/src/stories/components/Button.stories.tsx
  client/src/stories/components/Button.tsx
  client/src/types/api.ts
  client/src/types/auth.ts
  client/src/utils/localStorage.ts
  client/tailwind.config.js
  client/vite.config.ts
  server/app.ts
  server/handlers/authHandler.ts
  server/handlers/baseHandler.ts
  server/handlers/errorHandler.ts
  server/handlers/noteHandler.ts
  server/handlers/userHandler.ts
  server/middleware/noteMiddleware.ts
  server/models/Note.ts
  server/models/User.ts
  server/prettier.config.js
  server/routers/noteRouter.ts
  server/routers/userRouter.ts
  server/server.ts
  server/utils/APIFeatures.ts
  server/utils/AppError.ts
  server/utils/getTokenFromReq.ts
  server/utils/jwt.ts
Labels: enhancement

#30 fix button
  client/src/components/AuthForm/LogInForm.tsx
  client/src/components/AuthForm/SignUpForm.tsx
  client/src/components/Button/Button.tsx
  client/src/components/LabeledInput/LabeledInput.tsx
  client/src/components/RootLayout/Aside.tsx
  client/src/components/RootLayout/Header.tsx
  client/src/components/ThemeToggler/ThemeToggler.tsx
  client/src/pages/AuthPage.tsx
  client/src/pages/ErrorPage.tsx
  client/src/pages/UserProfilePage.tsx
  client/src/stories/components/Button.stories.tsx
  client/src/stories/components/LabeledInput.stories.tsx
Labels: fix

#31 add auth to form
  client/src/components/AuthForm/AuthForm.tsx
  client/src/components/AuthForm/LogInForm.tsx
  client/src/components/AuthForm/SignUpForm.tsx
  client/src/components/AuthForm/validateSchema.ts
  client/src/pages/AuthPage.tsx
Labels: enhancement

#35 raw note editor
  client/package.json
  client/src/App.tsx
  client/src/components/RootLayout/Aside.tsx
  client/src/components/RootLayout/index.tsx
  client/src/index.css
  client/src/pages/NoteEditorPage.tsx
  client/tailwind.config.js
  client/yarn.lock
Labels: enhancement

#36 29 theme logic with redux
  client/package.json
  client/src/App.tsx
  client/src/components/RootLayout/Header.tsx
  client/src/components/ThemeToggler/ThemeToggler.tsx
  client/src/contexts/ThemeContext.tsx
  client/src/lib/redux/rootReducer.ts
  client/src/lib/redux/slices/theme/themeSlice.ts
  client/src/lib/redux/store.ts
  client/src/main.tsx
  client/yarn.lock
Labels: enhancement

#39 basic note reducer
  client/src/App.tsx
  client/src/components/RootLayout/Aside.tsx
  client/src/lib/redux/rootReducer.ts
  client/src/lib/redux/slices/auth/authSlice.ts
  client/src/lib/redux/slices/auth/authThunk.ts
  client/src/lib/redux/slices/notes/notesSlice.ts
  client/src/lib/redux/slices/notes/notesThunk.ts
  client/src/lib/redux/slices/theme/themeSlice.ts
  client/src/pages/NoteEditorPage.tsx
  client/src/types/notes.ts
  server/handlers/noteHandler.ts
Labels: enhancement

#41 40 improve form links
  client/src/components/AuthForm/LogInForm.tsx
  client/src/components/AuthForm/SignUpForm.tsx
  client/src/index.css
  client/src/pages/AuthPage.tsx
Labels: fix

#42 add error page styled
  client/src/index.css
  client/src/pages/ErrorPage.tsx
Labels: enhancement

#43 notes
  client/src/App.tsx
  client/src/components/NoteEditor/FormattedView.tsx
  client/src/components/NoteEditor/NoteEditor.tsx
  client/src/components/NoteEditor/NoteHead.tsx
  client/src/components/RootLayout/Aside.tsx
  client/src/components/RootLayout/Header.tsx
  client/src/components/RootLayout/index.tsx
  client/src/index.css
  client/src/lib/redux/rootReducer.ts
  client/src/lib/redux/slices/noteEditor/noteEditorSlice.ts
  client/src/pages/NoteEditorPage.tsx
  client/src/utils/noteTags.ts
  client/vercel.json
Labels: enhancement
